# vim: sw=2:noai
---

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache=yes state=latest cache_valid_time=3600
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc

- name: Install Base Packages
  apt: name={{ item }} update_cache=yes force=yes state=installed cache_valid_time=3600
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python3-dev
    - python3-pip
    - python3-pycurl
    - supervisor

- name: Install latest (Python3) pip
  pip: name=pip executable=pip3 state=latest

- name: Install virtualenv
  pip: name=virtualenv state=latest
