---
# Git settings.
setup_git_repo: yes
git_branch: master

# application settings
project_path: "/webapps/{{ project_name }}"
virtualenv_path: "{{ project_path }}/venv"
application_log_dir: "{{ project_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"
nginx_server_name: 192.168.33.15

# Database settings.
db_user: "{{ application_name }}"
db_name: "{{ application_name }}"
db_password: password

# gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps
gunicorn_num_workers: 3
gunicorn_max_requests: 0
gunicorn_timeout_seconds: 300

# Nginx settings.
ssl_src_dir: ssl_self_signed
ssl_dest_dir: /etc/ssl
ssl_key_password: password
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ project_path }}/staticfiles/"
nginx_media_dir: "{{ project_path }}/media/"
#  nginx_server_name: "{{ inventory_hostname }}"
ssl_src_dir: ssl_self_signed
ssl_dest_dir: /etc/ssl
ssl_key_password: password

# Django settings.
django_settings_file: "{{ application_name }}.settings.production"
django_secret_key: "akr2icmg1n8%z^3fe3c+)5d0(t^cy-2_25rrl35a7@!scna^1#"
run_django_db_migrations: yes
run_django_collectstatic: yes

# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@127.0.0.1/{{ application_name }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"

