---

- name: Install additional packages required by django application
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libjpeg-dev 
    - zlib1g-dev
